/* Public customer experience. Demo state never represents a saved customer record. */
(()=>{
'use strict';
const escape=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const originalRender=render;
let session=null,ledger=[],ledgerError='',loading=false;
const campaign={stage:3,version:1,revision:false,invoice:false,messages:[],history:['Brand published the brief.','Agency assigned Thando.','Creator submitted version 1.']};
const roles=['creator','agency','brand'];
const known=['landing','login','signup','account','privacy','terms','security','availability','creator','agency','brand','journey'];
function action(label,command,disabled=false){return `<button class="cc-btn cc-primary" data-action="${command}" ${disabled?'disabled':''}>${label}</button>`;}
function status(text,error=false){const el=document.getElementById('customer-status');if(el){el.textContent=text;el.setAttribute('role',error?'alert':'status');}}
function mount(html){document.getElementById('cc-screen').innerHTML=`<section class="customer-main" id="main-content">${html}</section>`;}
function auth(signup){mount(`<section class="auth-panel"><span class="customer-pill">Creator accounts</span><h1>${signup?'Create your account':'Welcome back'}</h1><p>${signup?'Free during this release. Start with an empty income ledger. Agency and brand collaboration is currently available as a demo.':'Sign in to view your own saved transaction records.'}</p><form id="customer-auth" data-mode="${signup?'signup':'login'}">${signup?'<label for="auth-name">Full name</label><input id="auth-name" name="name" required minlength="2" maxlength="70" autocomplete="name">':''}<label for="auth-email">Email address</label><input id="auth-email" name="email" type="email" required maxlength="254" autocomplete="email"><label for="auth-password">Password${signup?' (8–128 characters)':''}</label><input id="auth-password" name="password" type="password" required ${signup?'minlength="8" maxlength="128"':''} autocomplete="${signup?'new-password':'current-password'}"><button class="cc-btn cc-primary" type="submit">${signup?'Create account':'Sign in'}</button><div id="customer-status" class="customer-status" role="status" aria-live="polite"></div></form><p>${signup?'Already registered? <a href="#login">Sign in</a>':'New here? <a href="#signup">Create a creator account</a>'}</p><p><a href="#creator">Try the demo without an account</a></p><p class="customer-meta">Read our <a href="#privacy">privacy notice</a> and <a href="#terms">service information</a> before creating an account.</p></section>`);}
function account(){if(!session){auth(false);return;}mount(`<div class="customer-actions"><h1>Your transaction ledger</h1>${action('Sign out','logout')}</div><p>Welcome, ${escape(session.name||session.email)}. These records come from your account; demo campaigns are kept separate.</p><div class="customer-actions">${action('Refresh records','refresh',loading)}${action('Export records (CSV)','export',!ledger.length)}</div><div id="customer-status" role="${ledgerError?'alert':'status'}" class="customer-status">${escape(ledgerError|| (loading?'Loading your records…':''))}</div>${!loading&&!ledgerError&&!ledger.length?'<div class="customer-card"><h2>No transactions yet</h2><p>Your account starts empty. No example income has been added. Add your first record below.</p></div>':''}<details class="customer-card"><summary>Add an income or expense record</summary><form id="customer-transaction" class="auth-panel"><label for="tx-kind">Type</label><select id="tx-kind" name="type"><option value="income">Income</option><option value="expense">Expense</option></select><label for="tx-source">Description</label><input id="tx-source" name="source" required maxlength="200"><label for="tx-amount">Amount (ZAR)</label><input id="tx-amount" name="amount" type="number" required min="0.01" max="999999999" step="0.01"><label for="tx-date">Date</label><input id="tx-date" name="date" type="date" required><button class="cc-btn cc-primary" type="submit">Save record</button><div class="customer-status" id="transaction-status" role="status" aria-live="polite"></div></form></details>${ledger.length?`<div class="customer-ledger-wrap"><table class="customer-ledger"><thead><tr><th>Date</th><th>Description</th><th>Type</th><th>Amount (ZAR)</th></tr></thead><tbody>${ledger.map(t=>`<tr><td>${escape(t.date)}</td><td>${escape(t.source||t.merchant)}</td><td>${escape(t.type)}</td><td>${Number(t.amount).toLocaleString('en-ZA',{minimumFractionDigits:2})}</td></tr>`).join('')}</tbody></table></div>`:''}`);}
const info={
privacy:['Privacy notice','Account data','Creator accounts use your name, email address and a password hash. Signing in returns a session token. This interface keeps that token in page memory; reloading the page requires signing in again.','Transaction records','The account view requests records associated with your authenticated user ID. Authentication and ledger services may use the configured Supabase database. Server logging and operational processing are separate from this browser interface.','Demo and external resources','Demo messages and approvals remain in this browser tab and reset on refresh. Do not enter confidential material into the demo. The site loads fonts from Google Fonts and icons from jsDelivr, which receive normal browser requests. No analytics or advertising tracking is added by this update.','Your privacy requests','Creator Cash Flow is the service operator. Email reamogetswemolefe@creatorcashflow.co.za to ask about records held, correction, deletion, retention or service providers. Do not include passwords or private financial records in your initial message. This notice is not a compliance certification.'],
terms:['Service information','Current availability','Creator sign-in and transaction retrieval use the account API. Agency, brand and shared campaign screens are demonstrations. Demo approvals, invoices, invitations and messages do not create contracts, transfer money or notify other people.','Financial information','Displayed demo amounts are illustrative. Records and exports are not certified receipts, tax advice or proof of payment. Content approval and payment status are separate.','Accounts and acceptable use','Use your own account credentials and do not upload material you are not entitled to share. Keep your password private. The interface does not currently offer self-service password recovery.','Free release and support','Creator accounts are free during this release. No subscription purchase or automatic payment is offered here. Contact Creator Cash Flow at reamogetswemolefe@creatorcashflow.co.za for support or an account closure request. Any future paid plan will need separate pricing and acceptance; no payment authorisation is collected in this flow.'],
security:['Security information','Controls in this release','The public interface uses the existing authentication API. The server verifies signed tokens before returning a user’s ledger. Passwords are hashed on the server. Inline click handlers have been replaced with registered listeners while retaining the browser security policy.','Limits','Security depends on deployment settings, database access controls and operational practices. No certification, uptime guarantee or POPIA compliance claim is made here.','Report an issue','Do not send passwords, tokens or private financial records. Report an issue to reamogetswemolefe@creatorcashflow.co.za.'],
availability:['What you can use today','Creator accounts','Create an account, sign in, add income and expense records, view your saved records and export them as CSV. New registrations are available only when durable account storage is configured in production.','Interactive demo','Explore creator, agency and brand views without registering. Try campaign feedback, review, revision and invoice-status transitions. Demo changes are temporary and stay in your current browser tab.','Not yet a live collaboration service','Agency invitations, multi-user campaign sharing, publishing, money movement and certified invoice downloads are not connected services in this release.','Pricing and support','Creator accounts are free during this release. For assistance, email reamogetswemolefe@creatorcashflow.co.za. No purchase or automatic billing is offered through this site.']};
function infoPage(key){const a=info[key];mount(`<h1>${a[0]}</h1>${a.slice(1).map((t,i)=>i%2===0?`<h2>${t}</h2>`:`<p>${t}</p>`).join('')}<p><a href="mailto:reamogetswemolefe@creatorcashflow.co.za">Email support or send a privacy request</a></p><p><a href="#landing">Back to the platform</a></p>`);}
function campaignPage(){const c=campaign,owner=c.revision?'Creator':stages[c.stage][0];mount(`<div class="customer-actions"><div><span class="customer-pill">Sample campaign · CCF-024</span><h1>Spring in motion</h1><p>Vela Active × Studio North × Thando Mokoena</p></div></div><div class="customer-grid"><section class="customer-card"><h2>Hero video · Version ${c.version}</h2><p>Instagram Reel · 30 seconds · 9:16<br>Draft: 16 September · Publish: 18 September</p><div class="customer-row"><span>Review status</span><strong>${c.revision?'Changes requested':c.stage<3?'In production':c.stage===3?'Agency review':c.stage===4?'Brand review':'Approved'}</strong></div><div class="customer-row"><span>Next owner</span><strong>${owner}</strong></div><h2>Brief & scope</h2><p>Show an outdoor movement routine featuring the spring collection. Include one Reel and three story frames. One consolidated revision; 30 days of organic reposting. Paid advertising rights are excluded from this sample brief.</p><div class="customer-actions">${action(c.invoice?'Invoice marked sent':c.revision?'Submit revised version':stages[c.stage][3],'campaign-next',c.invoice)}${[3,4].includes(c.stage)&&!c.revision?action('Request a revision','campaign-revise'):''}</div><div class="customer-row"><span>Creator fee</span><strong>R12,000 · sample</strong></div><div class="customer-row"><span>Invoice</span><strong>${c.invoice?'Sent · payment pending':'Not sent'}</strong></div><p class="customer-meta">Approval does not mark an invoice as paid. These actions only update this demo.</p><h2>Activity</h2><ol class="customer-history">${c.history.map(h=>`<li>${escape(h)}</li>`).join('')}</ol></section><section class="customer-card"><h2>Campaign conversation</h2><p>Use this thread to explore feedback between all three roles.</p><label for="campaign-role">Demo sender</label><select id="campaign-role"><option>Agency</option><option>Creator</option><option>Brand</option></select><div aria-live="polite">${c.messages.map(m=>`<div class="customer-demo-message"><strong>${escape(m.sender)}</strong><p>${escape(m.text)}</p></div>`).join('')}</div><form id="campaign-message"><label for="campaign-text">Feedback</label><textarea id="campaign-text" required maxlength="1000" placeholder="Add feedback to the sample campaign"></textarea><button class="cc-btn" type="submit">Add demo message</button></form><p class="customer-meta">No collaborator is notified. Refreshing resets this demonstration.</p></section></div>`);}
render=function(){
 const route=known.includes(state.page)?state.page:'landing';state.page=route;
 document.querySelector('.public-nav')?.classList.remove('is-open');document.querySelector('.mobile-menu')?.setAttribute('aria-expanded','false');
 if(route==='login'||route==='signup')auth(route==='signup');else if(route==='account')account();else if(info[route])infoPage(route);else if(route==='journey')campaignPage();else originalRender();
 const screen=document.getElementById('cc-screen');const demo=roles.includes(route)||route==='journey';
 document.getElementById('demo-notice')?.remove();if(demo){screen.insertAdjacentHTML('beforebegin',`<aside id="demo-notice" class="demo-notice"><strong>DEMO · Sample data</strong><span>Changes stay in this tab. No real approvals or payments.</span><select id="demo-perspective" aria-label="Demo perspective">${[...roles,'journey'].map(r=>`<option value="${r}" ${r===route?'selected':''}>${r==='journey'?'Shared campaign':r[0].toUpperCase()+r.slice(1)}</option>`).join('')}</select><a href="#landing">Exit demo</a></aside>`);}
 if(route==='landing'){screen.querySelectorAll('[data-command="setPage(\'login\')"]').forEach(e=>e.dataset.command="setPage('signup')");const intro=screen.querySelector('.ce-hero p');if(intro)intro.textContent='Track your creator income in one place. Explore our campaign collaboration demo for creators, agencies and brands.';}
 document.title=({landing:'Creator Cash Flow | Creator income and campaign collaboration',login:'Sign in | Creator Cash Flow',signup:'Create account | Creator Cash Flow'}[route]||route[0].toUpperCase()+route.slice(1)+' | Creator Cash Flow');
};
const oldSetPage=setPage;setPage=function(p){if(known.includes(p))oldSetPage(p);};
downloadInvoiceProof=function(){mount('<h1>Sample invoice</h1><p>This demo has no certified invoice or receipt to download. No document has been issued.</p><a href="#journey">Return to sample campaign</a>');};
approveBrandDeliverable=function(){campaign.stage=4;setPage('journey');};
sendChatMessage=function(){setPage('journey');};
function csvDownload(){const cell=v=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replace(/"/g,'""')+'"';const csv=[['Date','Description','Type','Amount (ZAR)'],...ledger.map(t=>[t.date,t.source||t.merchant,t.type,t.amount])].map(r=>r.map(cell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='creator-cash-flow-transactions.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function loadLedger(){if(!session)return;loading=true;ledgerError='';render();try{const r=await fetch('/api/transactions',{headers:{Authorization:'Bearer '+session.token}});if(r.status===401||r.status===403){session=null;ledger=[];setPage('login');status('Your session expired. Please sign in again.',true);return;}const data=await r.json();if(!r.ok)throw Error(data.error||'Could not load your records.');ledger=data.transactions||[];}catch(e){ledger=[];ledgerError=e.message;}finally{loading=false;if(state.page==='account')render();}}
document.addEventListener('click',e=>{
const el=e.target.closest('[data-command],[data-action]');if(!el)return;e.preventDefault();
if(el.dataset.action){const a=el.dataset.action;if(a==='menu'){const nav=document.querySelector('.public-nav');el.setAttribute('aria-expanded',nav.classList.toggle('is-open'));}if(a==='logout'){session=null;ledger=[];setPage('login');}if(a==='refresh')loadLedger();if(a==='export')csvDownload();if(a==='campaign-revise'){campaign.revision=true;campaign.history.push('Reviewer requested changes to the draft.');campaign.messages.push({sender:'Reviewer',text:'Please revise the outdoor opening to match the brief.'});render();}if(a==='campaign-next'){if(campaign.revision){campaign.version++;campaign.revision=false;campaign.stage=3;campaign.history.push('Creator submitted version '+campaign.version+'.');}else if(campaign.stage<5){campaign.history.push(stages[campaign.stage][0]+': '+stages[campaign.stage][3]+'.');campaign.stage++;}else{campaign.invoice=true;campaign.history.push('Creator marked the sample invoice as sent. Payment remains pending.');}render();}return;}
const command=el.dataset.command;const m=/^(\w+)\((?:'([^']*)'|(\d+))?\)$/.exec(command);if(!m)return;const name=m[1],arg=m[2]??m[3];const allowed={setPage,setWorkspaceTab,openCampaignFlow,setStep,nextStep,downloadInvoiceProof,approveBrandDeliverable,sendChatMessage,openTourDock:()=>setPage('creator'),executeDemoLogin:()=>setPage('creator'),alert:()=>{setPage('journey');}};if(Object.hasOwn(allowed,name))allowed[name](name==='setStep'?Number(arg):arg);
});
document.addEventListener('change',e=>{if(e.target.id==='demo-perspective')setPage(e.target.value);});
document.addEventListener('submit',async e=>{if(e.target.id==='customer-transaction'){e.preventDefault();if(!session){setPage('login');return;}const form=e.target,button=form.querySelector('button'),output=form.querySelector('#transaction-status');button.disabled=true;output.textContent='Saving…';try{const type=form.elements.type.value,description=form.elements.source.value.trim();const response=await fetch('/api/transactions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+session.token},body:JSON.stringify({type,source:description,merchant:description,amount:Number(form.elements.amount.value),date:form.elements.date.value,category:type==='income'?'Creator Revenue':'Operating Expense'})});const data=await response.json();if(!response.ok)throw Error(data.error||'The record could not be saved.');await loadLedger();status('Record saved.');}catch(err){output.textContent=err.message;output.setAttribute('role','alert');}finally{button.disabled=false;}return;}if(e.target.id==='campaign-message'){e.preventDefault();const text=document.getElementById('campaign-text').value.trim();if(text){campaign.messages.push({sender:document.getElementById('campaign-role').value,text});render();}return;}if(e.target.id!=='customer-auth')return;e.preventDefault();const form=e.target,button=form.querySelector('button'),mode=form.dataset.mode;button.disabled=true;status('Connecting securely…');const payload={email:form.email.value.trim(),password:form.password.value};if(mode==='signup')payload.name=form.elements.name.value.trim();try{const r=await fetch('/api/auth/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok||!data.token)throw Error(data.error||'Could not sign in. Please try again.');session={token:data.token,email:payload.email,name:data.user?.name||payload.name};form.reset();setPage('account');await loadLedger();}catch(err){status(err.message,true);}finally{button.disabled=false;}});
document.addEventListener('DOMContentLoaded',()=>{const logo=document.querySelector('.cc-logo')?.outerHTML||'<a href="#landing">Creator Cash Flow</a>';const header=document.querySelector('header');if(header)header.outerHTML=`<header class="public-header">${logo}<button class="mobile-menu" data-action="menu" aria-controls="public-nav" aria-expanded="false">Menu</button><nav id="public-nav" class="public-nav" aria-label="Main navigation"><a href="#landing">Product</a><a href="#availability">Availability</a><a href="#creator">Try the demo</a><a href="#login">Sign in</a><a class="primary-link" href="#signup">Get started</a></nav></header>`;document.querySelector('footer').outerHTML='<footer class="customer-footer"><span>© 2026 Creator Cash Flow</span><a href="#privacy">Privacy notice</a><a href="#terms">Service information</a><a href="#security">Security</a><a href="#availability">Free release & availability</a><a href="mailto:reamogetswemolefe@creatorcashflow.co.za">Contact support</a></footer>';const hash=location.hash.slice(1);state.page=known.includes(hash)?hash:'landing';window.addEventListener('hashchange',()=>{const h=location.hash.slice(1);if(known.includes(h)&&state.page!==h){state.page=h;render();}});render();});
})();
