const fs=require('fs'),path=require('path');
const sharp=require('C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root=__dirname,brand=path.resolve(root,'../../brand/connection-v2-stock');
const ink='#252F20',paper='#F7F7F2',lime='#DEFB82',sage='#A8B698';
const enc=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;');
const image=n=>'data:image/jpeg;base64,'+fs.readFileSync(path.join(brand,n+'-photo.jpg')).toString('base64');
function text(x,y,s,size=32,fill=ink,weight=400){return `<text x="${x}" y="${y}" font-family="Arial,sans-serif" font-size="${size}" font-weight="${weight}" fill="${fill}">${enc(s)}</text>`}
function lines(x,y,list,size=75,fill=ink,weight=700,leading=1.08){return list.map((s,i)=>text(x,y+i*size*leading,s,size,fill,weight)).join('')}
function rect(x,y,w,h,fill,r=0){return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${r}" fill="${fill}"/>`}
function logo(x=65,y=55,light=false,scale=1){const name=light?'approved-logo-paper.png':'approved-logo-ink.png';const data=fs.readFileSync(path.join(root,'assets',name)).toString('base64');return `<image x="${x}" y="${y}" width="${330*scale}" height="${120.2667*scale}" href="data:image/png;base64,${data}" preserveAspectRatio="xMidYMid meet"/>`}
function photo(name,x,y,w,h){return `<svg x="${x}" y="${y}" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><image href="${image(name)}" width="${w}" height="${h}" preserveAspectRatio="xMidYMid slice"/></svg>`}
function footer(y,w=1080,dark=false){return text(65,y,'GOOD WORK. CONNECTED.',19,dark?paper:ink,700)+text(w-365,y,'creatorcashflow.co.za',22,dark?paper:ink)}
function cta(x,y,label='Message us “PARTNER”',w=440){return rect(x,y,w,66,lime,33)+text(x+26,y+43,label,27,ink,700)}
async function save(name,w,h,body,bg=paper){const s=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><title>Creator Cash Flow — ${name}</title>${rect(0,0,w,h,bg)}${body}</svg>`;fs.writeFileSync(path.join(root,'editable',name+'.svg'),s);await sharp(Buffer.from(s)).png().toFile(path.join(root,'images',name+'.png'));}
async function main(){for(const d of ['editable','images','qa'])fs.mkdirSync(path.join(root,d),{recursive:true});
await save('01-agency-post',1080,1350,logo()+text(65,202,'FOR AGENCIES',22,ink,700)+lines(65,305,['Great talent.','One shared','direction.'],96)+text(65,574,'Let’s connect your next creator campaign.',31)+photo('team',0,635,1080,415)+rect(0,1050,1080,300,ink)+text(65,1114,'Partnership conversations start here.',29,paper)+cta(65,1150)+footer(1300,1080,true));
await save('02-brand-post',1080,1350,logo(65,55,true)+text(65,202,'FOR BRANDS',22,lime,700)+lines(65,303,['Your next','campaign.','Better connected.'],83,paper)+text(65,574,'Connect with the people behind the work.',30,paper)+photo('creator',0,635,1080,415)+text(65,1114,'Let’s talk creator partnerships.',30,paper)+cta(65,1150)+footer(1300,1080,true),ink);
await save('03-linkedin-post',1200,627,logo(55,35,false,.8)+text(55,176,'AGENCIES + BRANDS',19,ink,700)+lines(55,250,['Good work.','Connected.'],72)+lines(55,414,['A conversation about your next','creator campaign starts here.'],25,ink,400,1.35)+cta(55,501,'Message us “PARTNER”',410)+photo('team',755,0,445,627)+text(55,610,'creatorcashflow.co.za',19));
const slides=[
{head:['Your next creator','campaign starts','with connection.'],sub:['For agencies and brands ready','to start a better conversation.'],tag:'THE PARTNERSHIP CONVERSATION',photo:'team'},
{head:['Agencies,','bring your','perspective.'],sub:['What would make campaign coordination','simpler for your team and your creators?'],tag:'01 / THE AGENCY PERSPECTIVE',items:['Your roster.','Your process.','Your next campaign.']},
{head:['Brands,','bring your','ambition.'],sub:['What would help you connect a strong','brief to the people who can bring it to life?'],tag:'02 / THE BRAND PERSPECTIVE',items:['Your brief.','Your audience.','Your intended outcome.']},
{head:['Let’s talk about','the whole','campaign.'],sub:['From the first brief to the final invoice,','where does your team need more clarity?'],tag:'03 / THE SHARED CONVERSATION',items:['Briefs & responsibilities','Feedback & approvals','Invoices & payment visibility']},
{head:['Good work.','Connected.'],sub:['Tell us about your next creator campaign.','Let’s explore a partnership.'],tag:'LET’S START WITH YOUR TEAM',photo:'creator'}];
for(let i=0;i<slides.length;i++){let s=slides[i],dark=i===4,col=dark?paper:ink;let body=logo(65,55,dark)+text(65,205,s.tag,21,dark?lime:ink,700)+lines(65,318,s.head,78,col)+lines(65,654,s.sub,30,col,400,1.35);if(s.photo)body+=photo(s.photo,65,760,950,335);else body+=s.items.map((t,j)=>rect(65,775+j*105,950,85,j===0?lime:'#E8EDDF',12)+text(92,829+j*105,t,33,ink,500)).join('');if(i===4)body+=cta(65,1130);else body+=text(65,1179,'Continue the conversation →',25,col);body+=text(65,1298,'CREATOR CASH FLOW',19,col,700)+text(928,1298,`${i+1} / 5`,24,col);await save(`carousel-0${i+1}`,1080,1350,body,dark?ink:paper);}
await save('partnership-flyer',1240,1754,logo(75,60,false,1.15)+text(75,231,'AN INVITATION TO AGENCIES AND BRANDS',24,ink,700)+lines(75,357,['Good work.','Connected.'],110)+lines(75,565,['Let’s talk about your next','creator partnership.'],40,ink,400,1.25)+photo('team',0,691,1240,435)+rect(0,1126,1240,628,ink)+text(75,1200,'Bring your perspective to the conversation.',35,paper,700)+lines(75,1276,['Agencies: your roster, process and campaign challenges.','Brands: your brief, audience and intended outcome.'],28,paper,400,1.65)+lines(75,1405,['Campaign coordination. Approval clarity. Payment visibility.','Help shape a more connected way of working.'],29,paper,400,1.4)+cta(75,1516,'Explore a partnership',405)+text(75,1642,'creatorcashflow.co.za',34,paper,700)+text(75,1704,'Stock photograph: fauxels / Pexels. Illustrative subjects.',17,'#DDE2D7'));
const names=['01-agency-post','02-brand-post','03-linkedin-post',...slides.map((_,i)=>`carousel-0${i+1}`),'partnership-flyer'];let tiles=[];for(let i=0;i<names.length;i++){const b=await sharp(path.join(root,'images',names[i]+'.png')).resize(300,380,{fit:'contain',background:'#E5E8DF'}).png().toBuffer();tiles.push({input:b,left:(i%3)*320+20,top:Math.floor(i/3)*400+20});}await sharp({create:{width:980,height:1220,channels:3,background:'#E5E8DF'}}).composite(tiles).png().toFile(path.join(root,'campaign-overview.png'));console.log('Created 9 PNGs, 9 editable SVGs and campaign overview.');}
main().catch(e=>{console.error(e);process.exit(1)});
